### ISSUE TITLE
Facebook Graph API v2.3 being deprecated 7/10/17

### ISSUE THREAD

**Issue by broskoski** [artsy/artsy-passport#111]
The change that will affect us is:

> Nodes in the Graph API will return fewer fields by default. Use the 'fields' param to explicitly ask for the set of fields you want. If you ask for an explicit set of fields, the response will not contain any extra fields that you did not ask for

Specifically we will need to update `facebook-passport`, include the `email` field (like so: https://github.com/jaredhanson/passport-facebook#how-do-i-obtain-a-user-profile-with-specific-fields ) and ensure that the response shape is the same.

The changes will need to be made here https://github.com/artsy/artsy-passport/blob/master/lib/passport/index.coffee#L22 and here https://github.com/artsy/artsy-passport/blob/master/lib/passport/callbacks.coffee#L55

**Comment by broskoski** [comment]
cc @joeyAghion @craigspaeth

**Comment by craigspaeth** [comment]
Thanks for documenting this @broskoski!
