### ISSUE TITLE
The data in the session cookie is not encrypted

### ISSUE THREAD

**Issue by dblock** [artsy/artsy-passport#35]
The data in the session cookie contains the serialized user, with things like e-mail. It's a good idea to encrypt it rather than just base-64 encode it because if stolen it prevents leaking identity information, including security tokens (session can be replayed, but that's it).

**Comment by craigspaeth** [comment]
Investigating further I don't think this is an issue with Artsy passport. For one there is some level of encryption (or "signing"? I don't know the difference) happening in our session middleware ([this passport issue](https://github.com/jaredhanson/passport/issues/143) describes it). There's an issue open for the session middleware we use to encrypt cookies (https://github.com/expressjs/cookie-session/issues/9). If the "signing" happening in cookie-session isn't enough I think we just need to replace it with https://github.com/mozilla/node-client-sessions. That will probably result in us having to lose current sessions and log out all users. Lemme know if you think proceeding with that is the way to go and I'll swap the middleware in web apps.
